FROM public.ecr.aws/lambda/python:3.8

RUN yum -y update
RUN yum -y install gcc
RUN yum install -y git

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt \
    && pip install -e git://github.com/FraPochetti/mantisshrimp.git@aws-lambda#egg=icevision[inference] --upgrade -q

COPY model_dir ./model_dir

COPY /app/app.py   ./
CMD ["app.handler"] 