name: "unet"
platform: "tensorrt_plan"
max_batch_size: 1
input {
  name: "input"
  data_type: TYPE_FP32
  dims: 3
  dims: 512
  dims: 512
}
output {
  name: "output"
  data_type: TYPE_FP32
  dims: 2
  dims: 512
  dims: 512
}
instance_group {
  count: 1
  kind: KIND_GPU
}
model_warmup {
    name: "Warmup"
    batch_size: 1
    inputs: {
        key: "input"
        value: {
            data_type: TYPE_FP32
            dims: 3
            dims: 512
            dims: 512
            zero_data: false
        }
    }
}